config/routes.rb
Rails.application.routes.draw do

  resources :courses, :posts, :links, :notes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'courses#index'

  match '/searches/index', to: 'searches#index', via: ['post','get']

  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/updates', to: 'static_pages#updates', via: 'get'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  title            :string(50)       default("")
#  comment          :text
#  commentable_id   :integer
#  commentable_type :string(255)
#  user_id          :integer
#  role             :string(255)      default("comments")
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  teachers    :string(255)
#  gpa         :float
#  As          :float
#  Bs          :float
#  Cs          :float
#  Ds          :float
#  Fs          :float
#  created_at  :datetime
#  updated_at  :datetime
#

class Course < ActiveRecord::Base
  has_many :links
  has_many :posts
  has_many :notes
  validates :name, :description, presence: true



  def grade_distribution
    { 'A' => self.As, 'B' => self.Bs, 'C' => self.Cs, 'D' => self.Ds, 'F' => self.Fs }
  end
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  url         :string(255)
#  description :string(255)
#  course_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class UrlValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    begin
      require 'net/http'
      Net::HTTP.get(URI.parse(value))
    rescue Exception
      record.errors.add(:specific_url, "invalid url")
    end
  end
end


class Link < ActiveRecord::Base
  belongs_to :course

  validates :url, :presence => true, :url => true
  validates :name, :description, presence: true

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  course_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Note < ActiveRecord::Base
  belongs_to :course

  validates :title, :description, presence: true


end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :string(255)
#  course_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Post < ActiveRecord::Base
  belongs_to :course

  validates :title, :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end


  def edit
    @course_found = Course.find(params[:id])
    @link = Link.new()
    @post = Post.new()
  end

  def show
    redirect_to :edit
  end

  private

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def create
    link = Link.new(link_params)
    if link.save
      flash[:success] = "Thanks for contributing!"
    else
      flash[:danger] = link.errors.messages
    end
    redirect_to :back # Go back to page regardless
  end

  private

  def link_params
    params.require(:link).permit(:course_id, :url, :description, :name)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update]

  def index
    @notes = Note.all
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to note_path(@note)
    else
      flash[:danger] = @note.errors.messages
      redirect_to :back
    end
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def update
    unless @note.update_attributes(note_params)
      flash[:danger] = @note.errors.messages
      redirect_to :back
    else
      redirect_to action: :show
    end
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :description, :course_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = Post.new(post_params)
    if post.save
      flash[:success] = "Thanks for contributing"
    else
      flash[:danger] = post.errors.messages
    end
    redirect_to :back
  end

  private

  def post_params
    params.require(:post).permit(:course_id, :title, :description)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @results = search_results
  end

  private

  def search_results
    if params.has_key? :course
      Course.where("name like ?", "%#{params[:course][:name]}%")
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def updates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      language ||= 'markdown'
      CodeRay.scan(code, language).div(:line_numbers => :table)
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true,
      :tables => true,
      :highlight => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/links_helper.rb
module LinksHelper


end

app/helpers/notes_helper.rb
module NotesHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/_link_form.html.erb
  <% if @course_found.links.length >= 1 %>
    <%= @course_found.links.in_groups_of(3, false) do |group| %>
      <div class="row" id="links">
        <% group.each do |link| %>
          <div class="link link-tool-tip col-xs-12 col-sm-6 col-lg-4"
               data-toggle="tooltip" data-placement="top" title="<%=link.url%>">
            <a href="<%= link.url %>" class="list-group-item"  id="head">
              <i class="fa fa-external-link-square pull-right"></i>
              <p class="list-group-item-heading" id="head"><%= truncate link.name, length: 25 %></p>
              <p class="list-group-item-text lead"><%= link.description %></p>
            </a>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row no-links">
      <div class="text-danger col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1>No Links yet. Come back later or share your own</h1>
      </div>
    </div>
  <% end %>

<div class="row">
  <div class="col-xs-12 col-sm-9 col-lg-9" id="links">
    <h1>Post a helpful link <small> share a good study resource or note</small></h1>

    <%= form_for(@link, class: 'form-group') do |f| %>

      <%= f.text_field :url ,class:"form-control input-lg form-group", placeholder: "Url" %>

      <%= f.text_field :name, class:"form-control input-lg form-group", placeholder: "Name"  %>

      <%= f.text_field :description, class:"form-control input-lg form-group", placeholder: "Description" %>

      <%= f.hidden_field :course_id, value: @course_found.id %>

      <div class="form-group">
        <%= f.submit "Submit link", class: "btn btn-primary btn-lg btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/_note.html.erb
<div class="ol-xs-12 col-sm-6 col-lg-4 center-block">
  <a href="<%= new_note_path(course_id: @course_found.id) %>" class="btn btn-primary btn-lg note-new">
    <i class="fa fa-paperclip fa-5x"></i> New Note <br> <br>
  </a>
</div>
<% if @course_found.notes.length >= 1 %>
  <%= @course_found.notes.order('created_at ASC').in_groups_of(3, false) do |group| %>
    <div class="row" id="links">
      <% group.each do |note| %>
        <div class="link link-tool-tip col-xs-12 col-sm-6 col-lg-4">
          <a href="<%= note_path(note)%>" class="list-group-item">
            <i class="fa fa-external-link-square pull-right"></i>
            <p class="list-group-item-heading" id="head"><%= note.title %></p>
            <p class="list-group-item-text lead"><%= truncate(note.description, length: 100) %></p>
            <%= link_to 'View', note_path(note),class: "btn btn-primary btn-lg "%>
            <%= link_to 'Edit', edit_note_path(note),class: "btn btn-primary btn-lg " %>
          </a>
        </div>
      <% end %>_
    </div>
  <% end %>
<% else %>
  <div class="row no-links">
    <div class="text-danger col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <h1>No Links yet. Come back later or share your own</h1>
    </div>
  </div>
<% end %>

app/views/courses/_post_form.html.erb
  <% if @course_found.posts.length >= 1 %>
    <% @course_found.posts.order('created_at DESC').each do |post| %>
      <div class="row wrap">
        <div class="col-sm-12 col-md-12">
          <div class="panel panel-default <%= cycle('panel-info', 'panel-success') %>">
            <div class="panel-heading ">
              <h3 class="panel-title ">
                <i class="fa fa-pencil-square-o pull-right"></i><%=post.title  %></h3>
            </div>
            <div class="panel-body">
              <div class="alert">
                <h4><%= post.description %></h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="row no-links">
      <div class="text-danger col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1> No Comments yet. Come back later or share your own.</h1>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12 col-sm-9 col-lg-9" id="comments">
      <h1>Post a comment<small> any advice or tips?</small></h1>

      <%= form_for(@post, class: 'form-group') do |f| %>

        <%= f.text_field :title , class:"form-control input-lg_ form-group", placeholder: "Title" %>

        <%= f.text_area :description, class:"form-control input-lg form-group",rows: 5, placeholder: "Description"  %>

        <%= f.hidden_field :course_id, value: @course_found.id %>

        <div class="form-group">
          <%= f.submit "Submit comment", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/courses/edit.html.erb
<% columns = "col-xs-12 col-sm-12 col-md-12 col-lg-12" %>

<div class="row" id="home">
  <div class="<%= columns %>">
    <div class="jumbotron">
      <h1><%= @course_found.name %>   </h1>
      <h2><%= @course_found.description %> </h2>
      <p>Teachers: <%= @course_found.teachers %></p>
      <p>Average GPA from last semester: <%= number_with_precision(@course_found.gpa, precision: 2) %></p>
      <p>Grade Distribution from Spring 2014:</p>
      <%= pie_chart(@course_found.grade_distribution, height: '300px') %>
    </div>
  </div>
</div>

<ul class="nav nav-tabs">
  <li class="active"> <a class="btn btn-lg" href="#Notes" data-toggle="tab">
    <i class="fa fa-paperclip fa-2x pull-left"></i> Notes <br><br> </a>
  </li>
  <li> <a class="btn btn-lg" href="#Links" data-toggle="tab">
    <i class="fa fa-link fa-2x pull-left"></i> Links <br> <br></a>
  </li>
  <li> <a class="btn btn-lg" href="#Comments" data-toggle="tab">
    <i class="fa fa-comments fa-2x pull-left"></i> Comments <br><br> </a>
  </li>
</ul>

<div class="tab-content">
  <div id="Notes" class="tab-pane fade in active">
    <%= render 'courses/note' %>
  </div>
  <div id="Links" class="tab-pane fade in ">
    <%= render 'courses/link_form' %>
  </div>
  <div id="Comments" class="tab-pane fade">
    <%= render 'courses/post_form' %>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-lg-12">
    <div class="jumbotron">
      <h1> Select a class </h1>
    </div>
  </div>
</div>


<% @courses.in_groups_of(3, false) do |group| %>  <!--Takes groups of three courses -->
  <div class="row">
    <% group.each do |course| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <a href="<%= edit_course_path(course) %>">
          <div class="box">
            <div class="icon">
              <i class="fa fa-users fa-5x"></i>
              <div class="info">
                <h3 class="title"> <%= course.name %> </h3>
                <p>
                  <%= course.description %>
                </p>
                <div class="more">
                  <a href="<%= edit_course_path(course) %>" title="Title Link">
                    <i class="fa fa-plus"></i>
                    Details
                  </a>
                </div>
              </div>
            </div>
            <div class="space"></div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/courses/search.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-lg-12">
    <div class="jumbotron">
      <h1> <%= pluralize(@results.count, 'Result') %> found</h1>
    </div>
  </div>
</div>

<!-- Example row of columns -->
<%= @results.in_groups_of(3, false) do |group| %>
  <div class="row">
    <% group.each do |course| %>
    <div class="col-lg-4">
      <h3><%= course.name %></h3>
      <p> <%= course.description %> </p>
      <p><%= link_to 'View', edit_course_path(course), class: 'btn btn-primary'%></p>
    </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/ajn123/hokie_links">Source Code</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to 'Updates', updates_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Hokie Links', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
       </form>
      <%= form_for :course, url: { controller: 'searches', action: 'index' }, html: { class: "navbar-form navbar-right" }, role: "search" do |f| %>
        <div class="form-group" id="custom-templates">
          <%= f.text_field :name, placeholder: 'Search for classes...', class: "form-control typeahead", size: '30' %>
        </div>
        <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HokieLinks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

    <div class="container">
      <%= render 'layouts/header' %>

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/notes/_edit_note.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'View', note_path(@note),class: "btn btn-primary btn-lg ", data: { confirm: "Are you sure?, you will lose all changes made." } %></li>
  <li><%= f.submit class: "btn btn-primary btn-lg "  %> </li>
  <li><%= link_to 'Back to Course', edit_course_path(@note.course_id),class: "btn btn-primary btn-lg " %></li>
  <li><%= link_to 'Markdown Cheatsheet', 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet',class: "btn btn-primary btn-lg ", :target => "_blank" %></li>
</ol>

app/views/notes/_show_edit_bar.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Edit', edit_note_path(@note.id),class: "btn btn-primary btn-lg "  %></li>
  <li><%= link_to 'Back to Course', edit_course_path(@note.course_id),class: "btn btn-primary btn-lg " %></li>
</ol>

app/views/notes/edit.html.erb
<%= form_for(@note, url: { action: 'show' }) do |f| %>
  <%= render 'notes/edit_note', f: f %>

  <ol class="breadcrumb">
    <%= f.label 'Title:' %>
    <%= f.text_field :title %>
  </ol> <br>

  <%= f.text_area :description, class:"form-control input-lg form-group", rows: 30, placeholder: "Description" %>

  <%= render 'notes/edit_note', f: f %>
<% end %>

app/views/notes/index.html.erb
<h1>Notes#index</h1>
<p>Find me in app/views/notes/index.html.erb</p>


<% @notes.each do |note| %>
<%= note.title %>
<%= note.description %>

<%= link_to('edit', edit_note_path(note)) %>

<% end %>

app/views/notes/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Markdown Cheatsheet', 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet',class: "btn btn-primary btn-lg ", target: :blank%></li>
</ol>

<%= form_for(@note) do |f| %>

  <ol class="breadcrumb">
    <%= f.text_field :title, class:"form-control input-lg_form-group", placeholder: "Title" %>
  </ol>
  <%= f.text_area :description, class:"form-control input-lg form-group", rows: 20, placeholder: "Markdown" %>

  <%= f.hidden_field :course_id, value: params[:course_id] %>
  <div class="form-group">
    <%= f.submit "Save Note", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/notes/show.html.erb
<%= render 'notes/show_edit_bar' %>

<%= markdown(@note.description) %>

<%= render 'notes/show_edit_bar' %>

app/views/searches/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-lg-12">
    <div class="jumbotron">
      <% if @results %>
        <h1> <%= pluralize(@results.count, 'Result') %> found</h1>
      <% else %>
        <h1> No Results found</h1>
      <% end %>
    </div>
  </div>
</div>

<% if @results %>
  <%= @results.in_groups_of(3, false) do |group| %>
    <div class="row">
      <% group.each do |course| %>
        <div class="col-lg-4">
          <h3><%= course.name %></h3>
          <p> <%= course.description %> </p>
          <p><%= link_to 'View', edit_course_path(course), class: 'btn btn-primary'%></p>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>This site is dedicated to any student in need of help.</p>

app/views/static_pages/contact.html.erb
<h1>Coming soon</h1>

app/views/static_pages/index.html.erb
  <div class="text-center">
    <h1>Main Content</h1>
    <p class="lead">
      This template builds a simple navigation menu and static centered content.
      Easy to setup, yet flexible for further enhancements.
      <%= button_to('Get Started', courses_path, class:'btn btn-default', method: :get) %>
    </p>
  </div>

app/views/static_pages/updates.html.erb
<h1>Updates</h1>
<ul>
  <li> Added Actual GPAs from last semester</li>
  <li> Listed all teachers from last semester</li>
  <li> Ported all VT CS classes form Spring semester</li>
  <li> Added notes section</li>
</ul>